<?php
$data = array (
  array(
    "id" => "1",
    "name" => "Elvan Doner",
    "full_name" => "Elvan Döner",
    "email" => "elvandoner@gmail.com",
    "abbreviations" => "ED",
    "start-day" => "02/12/2022",
    "end-day" => " ",
    "position" => "intern",
    "manager" => "Beate Pettinger-Natmeßnig",
    "status" => array(
      array(
        "status-key" => "onboarding",
        array(
          "group-job" => "Vorbereitungen",
          array(
            "job-id" => "onboard01",
            "job-value" => "yes",
            "job-description" => "Vollständige Jobdescription in Workday hinterlegen",
            "job-postion" => "manager",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard02",
            "job-value" => " ",
            "job-description" => "Position in Workday anlegen",
            "job-postion" => "manager",
            "job-date" => "",
            "job-deadline" => "",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard03",
            "job-value" => " ",
            "job-description" => "Position in Workday genehmigen lassen",
            "job-postion" => "Local/Regional/Global",
            "job-date" => "",
            "job-deadline" => "",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard04",
            "job-value" => " ",
            "job-description" => "Unterlagen (Vertrag, Daten, Bewerbungsunterlagen, Lebenslauf) in Workday hochladen",
            "job-postion" => "Manager",
            "job-date" => "",
            "job-deadline" => "",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard05",
            "job-value" => " ",
            "job-description" => "Meldung an Krankenkassa",
            "job-postion" => "Finance PwC",
            "job-date" => "",
            "job-deadline" => "",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard06",
            "job-value" => " ",
            "job-description" => "Je nach Position Einrichtung SAP Zugang",
            "job-postion" => "Finance",
            "job-date" => "",
            "job-deadline" => "",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard07",
            "job-value" => " ",
            "job-description" => "Schulungsplan erstellen, ggf. Schulung in Hattersheim organisieren",
            "job-postion" => "Manager",
            "job-date" => "",
            "job-deadline" => "",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard07",
            "job-value" => " ",
            "job-description" => "Urlaubsanspruch prüfen: Tage",
            "job-postion" => "GM",
            "job-date" => "",
            "job-deadline" => "",
            "job-type" => "text",
          ),
          array(
            "job-id" => "onboard08",
            "job-value" => " ",
            "job-description" => "Unterweisung in allen positionsrelevanten Aufgaben und Systeme: Trainingsplan erstellen",
            "job-postion" => "Direkter Vorgesetzter",
            "job-date" => "",
            "job-deadline" => "",
            "job-type" => "check",
          )
        ),
        array(
          "group-job" => "Bei Eintritt innerhalb der Probezeit erledigen",
          array(
            "job-id" => "onboard09",
            "job-value" => "",
            "job-description" => "Zutrittskarte erstellen",
            "job-postion" => "AssGM",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard10",
            "job-value" => "",
            "job-description" => "Versand Announcement",
            "job-postion" => "Manager mit GM",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard11",
            "job-value" => "",
            "job-description" => "Lichtbildausweis kopieren",
            "job-postion" => "AssGM",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard12",
            "job-value" => "",
            "job-description" => "e card (Kopie)",
            "job-postion" => "Finance für Gehaltsverrechnung PwC",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard13",
            "job-value" => "",
            "job-description" => "Bankverbindung",
            "job-postion" => "Finance für Gehalt PwC",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard14",
            "job-value" => "",
            "job-description" => "Schul- und Ausbildungszeugnisse (ausgenommen Pflichtschulen, Firmenzeugnisse aller früheren Arbeitgeber )",
            "job-postion" => "AssGM",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard15",
            "job-value" => "",
            "job-description" => "Strafregisterauszug (ist beim zuständigen Polizeikommissariat u beantragen und muss bis zur Beendigung der Probezeit vorliegen)",
            "job-postion" => "AssGM",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard16",
            "job-value" => "",
            "job-description" => "Anforderung entsprechender Zugangsberechtigungn, Systeme und Passwörter ",
            "job-postion" => "IT",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard17",
            "job-value" => "",
            "job-description" => "Einweisung in das arbeitsplatzbedingte Umfeld",
            "job-postion" => "Vorgesetzter",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard18",
            "job-value" => "",
            "job-description" => "Bereitstellung/Anforderung von EDV wie Laptop/Station/Kabeln/Telefon",
            "job-postion" => "IT",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard19",
            "job-value" => "",
            "job-description" => "HRG Account anlegen",
            "job-postion" => "AssGM",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard20",
            "job-value" => "",
            "job-description" => "Anmeldung Gruppenkrankenversicherung",
            "job-postion" => "Finance",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard21",
            "job-value" => "",
            "job-description" => "Anmeldung Unfallversicherung",
            "job-postion" => "Finance",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard22",
            "job-value" => "",
            "job-description" => "Evtl. je nach Position Übergabe eines Firmenwagens mit entsprechender Policy  (Abgabe einer Führerscheinkopie) (Finance) Unterweisung KFZ Benutzung unterfertigen",
            "job-postion" => "Manager",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard23",
            "job-value" => "",
            "job-description" => "Je nach Position Aktualisierung Authorization Table",
            "job-postion" => "Finance",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard24",
            "job-value" => "",
            "job-description" => "Evtl. je nach Position Firmenkreditkarte",
            "job-postion" => "Finance",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard25",
            "job-value" => "",
            "job-description" => "Information über Gleitzeit bzw. Zeiterfassung",
            "job-postion" => "AssGM",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard26",
            "job-value" => "",
            "job-description" => "Übergabe von evtl. Devices wie Mobiltelefon, iPad... inkl. Policy",
            "job-postion" => "AssGM",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard27",
            "job-value" => "",
            "job-description" => "Information über relevante Betriebsvereinbarungen, siehe dazu auch Sharepoint Dokumente für Onboarding",
            "job-postion" => "Direkter Vorgesetzter",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard28",
            "job-value" => "",
            "job-description" => "Ggf: Dokumentenlager Berechtigung bei Reisswolf beantragen und Einschulung ins Webportal",
            "job-postion" => "Vorgesetzter",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard29",
            "job-value" => "",
            "job-description" => "Einweisung in das Thema Sicherheit und Gesundheit am Arbeitsplatz (Sicherheitsvertrauensperson) und Brandschutz",
            "job-postion" => "Brandschutzbeauftragte",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard30",
            "job-value" => "",
            "job-description" => "Visitenkarten, ggf Empfehlungskarten …",
            "job-postion" => "Marketing",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard31",
            "job-value" => "",
            "job-description" => "Signatur Outlook",
            "job-postion" => "Marketing",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard31",
            "job-value" => "",
            "job-description" => "PV-Abwesenheitsnotiz",
            "job-postion" => "Quality",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard32",
            "job-value" => "",
            "job-description" => "Zuweisung der Trainingsinhalte in Plateau",
            "job-postion" => "LQO",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard33",
            "job-value" => "",
            "job-description" => "Unterweisung zur Pharmakovigilanz/Medizinproduktevigilanz",
            "job-postion" => "Quality/LSO",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard34",
            "job-value" => "",
            "job-description" => "Unterschriftenliste aktualisieren",
            "job-postion" => "Quality/LSO",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard35",
            "job-value" => "",
            "job-description" => "Unterweisung in Datenschutz und Umgang mit Verträgen, Formulare (Anti-Korruption)",
            "job-postion" => "Compliance",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard36",
            "job-value" => "",
            "job-description" => "Unterweisung im Verhaltenskodex Pharmig und CSL Behring Verhaltenskodex inkl. Policys",
            "job-postion" => "Compliance",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard37",
            "job-value" => "",
            "job-description" => "Einweisung in allgemeine Themen: Verpflegung, Umgebung, Parken, Info Kurzparkzone",
            "job-postion" => "AssGM",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard38",
            "job-value" => "",
            "job-description" => "Einführung ins Intranet (iNet, askHR, ESS) ",
            "job-postion" => "IT",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard39",
            "job-value" => "",
            "job-description" => "Schulung Concur und Reisekostenordnung (Selbst am Sharepoint Austria: Links : Schulungen)",
            "job-postion" => "",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard40",
            "job-value" => "",
            "job-description" => "Anlage Bankverbindung in Concur",
            "job-postion" => "Selbst in Concur",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard41",
            "job-value" => "",
            "job-description" => "Einschulung ins FIORI",
            "job-postion" => "Manager",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard42",
            "job-value" => "",
            "job-description" => "Einschulung ARIBA, Dolphin ",
            "job-postion" => "Finance",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard43",
            "job-value" => "",
            "job-description" => "Rundmails: Zugang zu Gruppenverteilern",
            "job-postion" => "Manager",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard44",
            "job-value" => "",
            "job-description" => "Zugang Apps",
            "job-postion" => "Manager",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          )
        ),
        array(
          "group-job" => "Nach Probezeit",
          array(
            "job-id" => "onboard45",
            "job-value" => "",
            "job-description" => "Überwachung Probezeit, Unterschriftenberechtigung im Anschluss, Vertrag",
            "job-postion" => "Direkter Vorgesetzter",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard46",
            "job-value" => "",
            "job-description" => " ",
            "job-postion" => "manager",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "textarea",
          ),
        ),
        array(
          "employee-signature" => "",
          "signature-manager" => "",
        )
      ),
      array(
        "status-key" => "offboarding",
        array(
          "group-job" => "Vorbereitungen",
          array(
            "job-id" => "offboarding01",
            "job-value" => "",
            "job-description" => "Rückgabe Firmenwagen,  Zutritt Parken, Schlüssel, Tankkarte + Info Reifenlagerung",
            "job-postion" => "Finance",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "offboarding02",
            "job-value" => "",
            "job-description" => "Rückgabe Kreditkarte, Rückzahlung RK-Vorschuss",
            "job-postion" => "Finance",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "offboarding03",
            "job-value" => "",
            "job-description" => "Rückgabe Zutrittskarte und ggf. Zutrittsschlüssel",
            "job-postion" => "Ass Gm",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "offboarding04",
            "job-value" => "",
            "job-description" => "Meldungen hinsichtlich Krankenkasse",
            "job-postion" => "Finance PwC",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "offboarding05",
            "job-value" => "",
            "job-description" => "Übernahme oder Abmeldung Gruppenkrankenkassa",
            "job-postion" => "Finance",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "offboarding06",
            "job-value" => "",
            "job-description" => "Abmeldung Unfallversicherung",
            "job-postion" => "Finance",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "offboarding07",
            "job-value" => "",
            "job-description" => "Ggf Dokumentlager Reisswolf: Account löschen",
            "job-postion" => "GM",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "offboarding08",
            "job-value" => "",
            "job-description" => "Rückgabe Firmenbesitz (Laptop, iPad, iPhone (AssGM) Roll-ups, Werbematerial",
            "job-postion" => "GM",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "offboarding09",
            "job-value" => "",
            "job-description" => "IAMS: Löschen K-Zugriff",
            "job-postion" => "Finance",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "offboarding10",
            "job-value" => "",
            "job-description" => "Schlüssel (Rollcontainer, Aktenschrank etc)",
            "job-postion" => "Manager",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "offboarding11",
            "job-value" => "",
            "job-description" => "Systemzutritte löschen (SAP, ggf Bürgerkarte, ggf Firmenbuch)",
            "job-postion" => "IT/GM",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "offboarding12",
            "job-value" => "",
            "job-description" => "Abschließen des Austritts in Workday",
            "job-postion" => "Manager",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "offboarding13",
            "job-value" => "",
            "job-description" => "",
            "job-postion" => "",
            "job-date" => "",
            "job-deadline" => "",
            "job-type" => "textarea",
          ),
        ),
        array(
          "employee-signature" => "",
          "signature-manager" => "",
        )
      ),
      array(
        "status-key" => "Maternity Leave",
        array(
          "group-job" => "Vorbereitungen",
          array(
            "job-id" => "maternity01",
            "job-value" => "yes",
            "job-description" => "Vollständige Jobdescription in Workday hinterlegen",
            "job-postion" => "Manager",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity02",
            "job-value" => "",
            "job-description" => "Position in Workday anlegen ",
            "job-postion" => "Manager",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity03",
            "job-value" => "",
            "job-description" => "Position in Workday genehmigen lassen",
            "job-postion" => array ("Local","Regional","Global"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity04",
            "job-value" => "",
            "job-description" => "Unterlagen (Vertrag, Daten, Bewerbungsunterlagen, Lebenslauf) in Workday hochladen",
            "job-postion" => array ("Manager"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity05",
            "job-value" => "",
            "job-description" => "Meldung an Krankenkassa ",
            "job-postion" => array ("Finance PwC"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity06",
            "job-value" => "",
            "job-description" => "Schulungsplan erstellen, ggf. Schulung in Hattersheim organisieren",
            "job-postion" => array ("Manager"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity07",
            "job-value" => " ",
            "job-description" => "Urlaubsanspruch prüfen: Tage",
            "job-postion" => array ("GM"),
            "job-date" => "",
            "job-deadline" => "",
            "job-type" => "text",
          ),
          array(
            "job-id" => "maternity08",
            "job-value" => "",
            "job-description" => "Unterweisung in allen positionsrelevanten Aufgaben und Systeme: Trainingsplan erstellen",
            "job-postion" => array ("Direkter Vorgesetzter"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
        ),
        array(
          "group-job" => "Bei Eintritt innerhalb der Probezeit erledigen",
          array(
            "job-id" => "maternity09",
            "job-value" => "",
            "job-description" => "Zutrittskarte erstellen ",
            "job-postion" => array ("Manager"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity10",
            "job-value" => "",
            "job-description" => "Versand Announcement",
            "job-postion" => array ("Manager mit GM"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity11",
            "job-value" => "",
            "job-description" => "Anforderung entsprechender Zugangsberechtigungn, Systeme und Passwörter",
            "job-postion" => array ("IT"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity12",
            "job-value" => "",
            "job-description" => "Einweisung in das arbeitsplatzbedingte Umfeld",
            "job-postion" => array ("Vorgesetzter"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity13",
            "job-value" => "",
            "job-description" => "Bereitstellung/Anforderung von EDV wie Laptop/Station/Kabeln/Telefon",
            "job-postion" => array ("IT"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity14",
            "job-value" => "",
            "job-description" => "Je nach Position Aktualisierung Authorization Table",
            "job-postion" => array ("Finance"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity15",
            "job-value" => "",
            "job-description" => "Information über Gleitzeit bzw. Zeiterfassung",
            "job-postion" => array ("AssGM"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity16",
            "job-value" => "",
            "job-description" => "Übergabe von evtl. Devices wie Mobiltelefon, iPad... inkl. Policy",
            "job-postion" => array ("AssGM"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity17",
            "job-value" => "",
            "job-description" => "Information über relevante Betriebsvereinbarungen, siehe dazu auch Sharepoint Dokumente für Onboarding",
            "job-postion" => array ("Direkter Vorgesetzter"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity18",
            "job-value" => "",
            "job-description" => "Aufsetzen von Zielen",
            "job-postion" => array ("Direkter Vorgesetzter"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity19",
            "job-value" => "",
            "job-description" => "Visitenkarten, ggf Empfehlungskarten …",
            "job-postion" => array ("Marketing"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity20",
            "job-value" => "",
            "job-description" => "Signatur Outlook",
            "job-postion" => array ("Marketing"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity21",
            "job-value" => "",
            "job-description" => "PV-Abwesenheitsnotiz",
            "job-postion" => array ("Quality"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity22",
            "job-value" => "",
            "job-description" => "Zuweisung der Trainingsinhalte in Plateau",
            "job-postion" => array ("LQO"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity23",
            "job-value" => "",
            "job-description" => "Unterweisung in Datenschutz und Umgang mit Verträgen, Formulare (Anti-Korruption)",
            "job-postion" => array ("Compliance"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity24",
            "job-value" => "",
            "job-description" => "Einschulung ins FIORI",
            "job-postion" => array ("Manager"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity25",
            "job-value" => "",
            "job-description" => "Einschulung ARIBA, Dolphin",
            "job-postion" => array ("Finance"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity26",
            "job-value" => "",
            "job-description" => "Rundmails: Zugang zu Gruppenverteilern",
            "job-postion" => array ("Manager"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity27",
            "job-value" => "",
            "job-description" => "Zugang Apps",
            "job-postion" => array ("Marketing"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
        ),
        array(
          "group-job" => "Nach Probezeit",
          array(
            "job-id" => "maternity28",
            "job-value" => "",
            "job-description" => "",
            "job-postion" => "",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "textarea",
          ),
        ),
        array(
          "employee-signature" => "",
          "signature-manager" => "",
        ),
      ),
    )
  ),
  array(
    "id" => "20",
    "name" => "codemenschen",
    "full_name" => "codemenschen",
    "email" => "codemenschen@gmail.com",
    "abbreviations" => "ED",
    "start-day" => " ",
    "end-day" => " ",
    "position" => "intern",
    "manager" => "Beate Pettinger-Natmeßnig",
    "status" => array(
      array(
        "status-key" => "onboarding",
        array(
          "group-job" => "Vorbereitungen",
          array(
            "job-id" => "onboard01",
            "job-value" => "yes",
            "job-description" => "Vollständige Jobdescription in Workday hinterlegen",
            "job-postion" => "manager",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard02",
            "job-value" => " ",
            "job-description" => "Position in Workday anlegen",
            "job-postion" => "manager",
            "job-date" => "",
            "job-deadline" => "",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard03",
            "job-value" => " ",
            "job-description" => "Position in Workday genehmigen lassen",
            "job-postion" => "Local/Regional/Global",
            "job-date" => "",
            "job-deadline" => "",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard04",
            "job-value" => " ",
            "job-description" => "Unterlagen (Vertrag, Daten, Bewerbungsunterlagen, Lebenslauf) in Workday hochladen",
            "job-postion" => "Manager",
            "job-date" => "",
            "job-deadline" => "",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard05",
            "job-value" => " ",
            "job-description" => "Meldung an Krankenkassa",
            "job-postion" => "Finance PwC",
            "job-date" => "",
            "job-deadline" => "",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard06",
            "job-value" => " ",
            "job-description" => "Je nach Position Einrichtung SAP Zugang",
            "job-postion" => "Finance",
            "job-date" => "",
            "job-deadline" => "",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard07",
            "job-value" => " ",
            "job-description" => "Schulungsplan erstellen, ggf. Schulung in Hattersheim organisieren",
            "job-postion" => "Manager",
            "job-date" => "",
            "job-deadline" => "",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard07",
            "job-value" => " ",
            "job-description" => "Urlaubsanspruch prüfen: Tage",
            "job-postion" => "GM",
            "job-date" => "",
            "job-deadline" => "",
            "job-type" => "text",
          ),
          array(
            "job-id" => "onboard08",
            "job-value" => " ",
            "job-description" => "Unterweisung in allen positionsrelevanten Aufgaben und Systeme: Trainingsplan erstellen",
            "job-postion" => "Direkter Vorgesetzter",
            "job-date" => "",
            "job-deadline" => "",
            "job-type" => "check",
          )
        ),
        array(
          "group-job" => "Bei Eintritt innerhalb der Probezeit erledigen",
          array(
            "job-id" => "onboard09",
            "job-value" => "",
            "job-description" => "Zutrittskarte erstellen",
            "job-postion" => "AssGM",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard10",
            "job-value" => "",
            "job-description" => "Versand Announcement",
            "job-postion" => "Manager mit GM",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard11",
            "job-value" => "",
            "job-description" => "Lichtbildausweis kopieren",
            "job-postion" => "AssGM",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard12",
            "job-value" => "",
            "job-description" => "e card (Kopie)",
            "job-postion" => "Finance für Gehaltsverrechnung PwC",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard13",
            "job-value" => "",
            "job-description" => "Bankverbindung",
            "job-postion" => "Finance für Gehalt PwC",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard14",
            "job-value" => "",
            "job-description" => "Schul- und Ausbildungszeugnisse (ausgenommen Pflichtschulen, Firmenzeugnisse aller früheren Arbeitgeber )",
            "job-postion" => "AssGM",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard15",
            "job-value" => "",
            "job-description" => "Strafregisterauszug (ist beim zuständigen Polizeikommissariat u beantragen und muss bis zur Beendigung der Probezeit vorliegen)",
            "job-postion" => "AssGM",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard16",
            "job-value" => "",
            "job-description" => "Anforderung entsprechender Zugangsberechtigungn, Systeme und Passwörter ",
            "job-postion" => "IT",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard17",
            "job-value" => "",
            "job-description" => "Einweisung in das arbeitsplatzbedingte Umfeld",
            "job-postion" => "Vorgesetzter",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard18",
            "job-value" => "",
            "job-description" => "Bereitstellung/Anforderung von EDV wie Laptop/Station/Kabeln/Telefon",
            "job-postion" => "IT",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard19",
            "job-value" => "",
            "job-description" => "HRG Account anlegen",
            "job-postion" => "AssGM",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard20",
            "job-value" => "",
            "job-description" => "Anmeldung Gruppenkrankenversicherung",
            "job-postion" => "Finance",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard21",
            "job-value" => "",
            "job-description" => "Anmeldung Unfallversicherung",
            "job-postion" => "Finance",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard22",
            "job-value" => "",
            "job-description" => "Evtl. je nach Position Übergabe eines Firmenwagens mit entsprechender Policy  (Abgabe einer Führerscheinkopie) (Finance) Unterweisung KFZ Benutzung unterfertigen",
            "job-postion" => "Manager",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard23",
            "job-value" => "",
            "job-description" => "Je nach Position Aktualisierung Authorization Table",
            "job-postion" => "Finance",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard24",
            "job-value" => "",
            "job-description" => "Evtl. je nach Position Firmenkreditkarte",
            "job-postion" => "Finance",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard25",
            "job-value" => "",
            "job-description" => "Information über Gleitzeit bzw. Zeiterfassung",
            "job-postion" => "AssGM",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard26",
            "job-value" => "",
            "job-description" => "Übergabe von evtl. Devices wie Mobiltelefon, iPad... inkl. Policy",
            "job-postion" => "AssGM",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard27",
            "job-value" => "",
            "job-description" => "Information über relevante Betriebsvereinbarungen, siehe dazu auch Sharepoint Dokumente für Onboarding",
            "job-postion" => "Direkter Vorgesetzter",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard28",
            "job-value" => "",
            "job-description" => "Ggf: Dokumentenlager Berechtigung bei Reisswolf beantragen und Einschulung ins Webportal",
            "job-postion" => "Vorgesetzter",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard29",
            "job-value" => "",
            "job-description" => "Einweisung in das Thema Sicherheit und Gesundheit am Arbeitsplatz (Sicherheitsvertrauensperson) und Brandschutz",
            "job-postion" => "Brandschutzbeauftragte",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard30",
            "job-value" => "",
            "job-description" => "Visitenkarten, ggf Empfehlungskarten …",
            "job-postion" => "Marketing",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard31",
            "job-value" => "",
            "job-description" => "Signatur Outlook",
            "job-postion" => "Marketing",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard31",
            "job-value" => "",
            "job-description" => "PV-Abwesenheitsnotiz",
            "job-postion" => "Quality",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard32",
            "job-value" => "",
            "job-description" => "Zuweisung der Trainingsinhalte in Plateau",
            "job-postion" => "LQO",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard33",
            "job-value" => "",
            "job-description" => "Unterweisung zur Pharmakovigilanz/Medizinproduktevigilanz",
            "job-postion" => "Quality/LSO",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard34",
            "job-value" => "",
            "job-description" => "Unterschriftenliste aktualisieren",
            "job-postion" => "Quality/LSO",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard35",
            "job-value" => "",
            "job-description" => "Unterweisung in Datenschutz und Umgang mit Verträgen, Formulare (Anti-Korruption)",
            "job-postion" => "Compliance",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard36",
            "job-value" => "",
            "job-description" => "Unterweisung im Verhaltenskodex Pharmig und CSL Behring Verhaltenskodex inkl. Policys",
            "job-postion" => "Compliance",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard37",
            "job-value" => "",
            "job-description" => "Einweisung in allgemeine Themen: Verpflegung, Umgebung, Parken, Info Kurzparkzone",
            "job-postion" => "AssGM",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard38",
            "job-value" => "",
            "job-description" => "Einführung ins Intranet (iNet, askHR, ESS) ",
            "job-postion" => "IT",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard39",
            "job-value" => "",
            "job-description" => "Schulung Concur und Reisekostenordnung (Selbst am Sharepoint Austria: Links : Schulungen)",
            "job-postion" => "",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard40",
            "job-value" => "",
            "job-description" => "Anlage Bankverbindung in Concur",
            "job-postion" => "Selbst in Concur",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard41",
            "job-value" => "",
            "job-description" => "Einschulung ins FIORI",
            "job-postion" => "Manager",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard42",
            "job-value" => "",
            "job-description" => "Einschulung ARIBA, Dolphin ",
            "job-postion" => "Finance",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard43",
            "job-value" => "",
            "job-description" => "Rundmails: Zugang zu Gruppenverteilern",
            "job-postion" => "Manager",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard44",
            "job-value" => "",
            "job-description" => "Zugang Apps",
            "job-postion" => "Manager",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          )
        ),
        array(
          "group-job" => "Nach Probezeit",
          array(
            "job-id" => "onboard45",
            "job-value" => "",
            "job-description" => "Überwachung Probezeit, Unterschriftenberechtigung im Anschluss, Vertrag",
            "job-postion" => "Direkter Vorgesetzter",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "onboard46",
            "job-value" => "",
            "job-description" => " ",
            "job-postion" => "manager",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "textarea",
          ),
        ),
        array(
          "employee-signature" => "",
          "signature-manager" => "",
        )
      ),
      array(
        "status-key" => "offboarding",
        array(
          "group-job" => "Vorbereitungen",
          array(
            "job-id" => "offboarding01",
            "job-value" => "",
            "job-description" => "Rückgabe Firmenwagen,  Zutritt Parken, Schlüssel, Tankkarte + Info Reifenlagerung",
            "job-postion" => "Finance",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "offboarding02",
            "job-value" => "",
            "job-description" => "Rückgabe Kreditkarte, Rückzahlung RK-Vorschuss",
            "job-postion" => "Finance",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "offboarding03",
            "job-value" => "",
            "job-description" => "Rückgabe Zutrittskarte und ggf. Zutrittsschlüssel",
            "job-postion" => "Ass Gm",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "offboarding04",
            "job-value" => "",
            "job-description" => "Meldungen hinsichtlich Krankenkasse",
            "job-postion" => "Finance PwC",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "offboarding05",
            "job-value" => "",
            "job-description" => "Übernahme oder Abmeldung Gruppenkrankenkassa",
            "job-postion" => "Finance",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "offboarding06",
            "job-value" => "",
            "job-description" => "Abmeldung Unfallversicherung",
            "job-postion" => "Finance",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "offboarding07",
            "job-value" => "",
            "job-description" => "Ggf Dokumentlager Reisswolf: Account löschen",
            "job-postion" => "GM",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "offboarding08",
            "job-value" => "",
            "job-description" => "Rückgabe Firmenbesitz (Laptop, iPad, iPhone (AssGM) Roll-ups, Werbematerial",
            "job-postion" => "GM",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "offboarding09",
            "job-value" => "",
            "job-description" => "IAMS: Löschen K-Zugriff",
            "job-postion" => "Finance",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "offboarding10",
            "job-value" => "",
            "job-description" => "Schlüssel (Rollcontainer, Aktenschrank etc)",
            "job-postion" => "Manager",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "offboarding11",
            "job-value" => "",
            "job-description" => "Systemzutritte löschen (SAP, ggf Bürgerkarte, ggf Firmenbuch)",
            "job-postion" => "IT/GM",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "offboarding12",
            "job-value" => "",
            "job-description" => "Abschließen des Austritts in Workday",
            "job-postion" => "Manager",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "offboarding13",
            "job-value" => "",
            "job-description" => "",
            "job-postion" => "",
            "job-date" => "",
            "job-deadline" => "",
            "job-type" => "textarea",
          ),
        ),
        array(
          "employee-signature" => "",
          "signature-manager" => "",
        )
      ),
      array(
        "status-key" => "Maternity Leave",
        array(
          "group-job" => "Vorbereitungen",
          array(
            "job-id" => "maternity01",
            "job-value" => "yes",
            "job-description" => "Vollständige Jobdescription in Workday hinterlegen",
            "job-postion" => "Manager",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity02",
            "job-value" => "",
            "job-description" => "Position in Workday anlegen ",
            "job-postion" => "Manager",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity03",
            "job-value" => "",
            "job-description" => "Position in Workday genehmigen lassen",
            "job-postion" => array ("Local","Regional","Global"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity04",
            "job-value" => "",
            "job-description" => "Unterlagen (Vertrag, Daten, Bewerbungsunterlagen, Lebenslauf) in Workday hochladen",
            "job-postion" => array ("Manager"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity05",
            "job-value" => "",
            "job-description" => "Meldung an Krankenkassa ",
            "job-postion" => array ("Finance PwC"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity06",
            "job-value" => "",
            "job-description" => "Schulungsplan erstellen, ggf. Schulung in Hattersheim organisieren",
            "job-postion" => array ("Manager"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity07",
            "job-value" => " ",
            "job-description" => "Urlaubsanspruch prüfen: Tage",
            "job-postion" => array ("GM"),
            "job-date" => "",
            "job-deadline" => "",
            "job-type" => "text",
          ),
          array(
            "job-id" => "maternity08",
            "job-value" => "",
            "job-description" => "Unterweisung in allen positionsrelevanten Aufgaben und Systeme: Trainingsplan erstellen",
            "job-postion" => array ("Direkter Vorgesetzter"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
        ),
        array(
          "group-job" => "Bei Eintritt innerhalb der Probezeit erledigen",
          array(
            "job-id" => "maternity09",
            "job-value" => "",
            "job-description" => "Zutrittskarte erstellen ",
            "job-postion" => array ("Manager"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity10",
            "job-value" => "",
            "job-description" => "Versand Announcement",
            "job-postion" => array ("Manager mit GM"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity11",
            "job-value" => "",
            "job-description" => "Anforderung entsprechender Zugangsberechtigungn, Systeme und Passwörter",
            "job-postion" => array ("IT"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity12",
            "job-value" => "",
            "job-description" => "Einweisung in das arbeitsplatzbedingte Umfeld",
            "job-postion" => array ("Vorgesetzter"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity13",
            "job-value" => "",
            "job-description" => "Bereitstellung/Anforderung von EDV wie Laptop/Station/Kabeln/Telefon",
            "job-postion" => array ("IT"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity14",
            "job-value" => "",
            "job-description" => "Je nach Position Aktualisierung Authorization Table",
            "job-postion" => array ("Finance"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity15",
            "job-value" => "",
            "job-description" => "Information über Gleitzeit bzw. Zeiterfassung",
            "job-postion" => array ("AssGM"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity16",
            "job-value" => "",
            "job-description" => "Übergabe von evtl. Devices wie Mobiltelefon, iPad... inkl. Policy",
            "job-postion" => array ("AssGM"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity17",
            "job-value" => "",
            "job-description" => "Information über relevante Betriebsvereinbarungen, siehe dazu auch Sharepoint Dokumente für Onboarding",
            "job-postion" => array ("Direkter Vorgesetzter"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity18",
            "job-value" => "",
            "job-description" => "Aufsetzen von Zielen",
            "job-postion" => array ("Direkter Vorgesetzter"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity19",
            "job-value" => "",
            "job-description" => "Visitenkarten, ggf Empfehlungskarten …",
            "job-postion" => array ("Marketing"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity20",
            "job-value" => "",
            "job-description" => "Signatur Outlook",
            "job-postion" => array ("Marketing"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity21",
            "job-value" => "",
            "job-description" => "PV-Abwesenheitsnotiz",
            "job-postion" => array ("Quality"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity22",
            "job-value" => "",
            "job-description" => "Zuweisung der Trainingsinhalte in Plateau",
            "job-postion" => array ("LQO"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity23",
            "job-value" => "",
            "job-description" => "Unterweisung in Datenschutz und Umgang mit Verträgen, Formulare (Anti-Korruption)",
            "job-postion" => array ("Compliance"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity24",
            "job-value" => "",
            "job-description" => "Einschulung ins FIORI",
            "job-postion" => array ("Manager"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity25",
            "job-value" => "",
            "job-description" => "Einschulung ARIBA, Dolphin",
            "job-postion" => array ("Finance"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity26",
            "job-value" => "",
            "job-description" => "Rundmails: Zugang zu Gruppenverteilern",
            "job-postion" => array ("Manager"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
          array(
            "job-id" => "maternity27",
            "job-value" => "",
            "job-description" => "Zugang Apps",
            "job-postion" => array ("Marketing"),
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "check",
          ),
        ),
        array(
          "group-job" => "Nach Probezeit",
          array(
            "job-id" => "maternity28",
            "job-value" => "",
            "job-description" => "",
            "job-postion" => "",
            "job-date" => "02/12/2022",
            "job-deadline" => "07/12/2022",
            "job-type" => "textarea",
          ),
        ),
        array(
          "employee-signature" => "",
          "signature-manager" => "",
        ),
      ),
    )
  )
);
// echo '<pre>';
// var_dump($data);
// echo '</pre>';
 ?>